"use client"
import { Navbar } from '@/components/Navigation/Navbar'
import './globals.scss'
import { Montserrat } from 'next/font/google'
import {Footer} from '@/components/Footer/Footer'
import { AnimatePresence, motion } from 'framer-motion'

const mont = Montserrat({ 
  subsets: ['latin'],
  variable: '--font-mont'
 })

export const metadata = {
  title: 'Introduction',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: JSX.Element,
}) {
  return (
    <html lang="en">
      <body className={`${mont.className} bg-light w-full min-h-screen`}>
        <Navbar/>
        <AnimatePresence>
          <motion.div>{children}</motion.div>
        </AnimatePresence>    
        <Footer/>
      </body>
    </html>
  )
}


