import { Navbar } from '@/components/Navigation/Navbar'
import './globals.scss'
import { Montserrat } from 'next/font/google'
import {Footer} from '@/components/Footer/Footer'

const mont = Montserrat({ 
  subsets: ['latin'],
  variable: '--font-mont'
 })

export const metadata = {
  title: 'Introduction',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${mont.className} bg-light w-full min-h-screen`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}


